version: '3'

services:
  drone-server:
    image: drone/drone
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    volumes:
      - ./drone-data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file: .drone.env
    environment:
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_RUNNER_CAPACITY=2

networks:
  default:
    driver: bridge
